Enhancement: API Keys Management
faradayafrica/Univast pull request #28
Opened 2023-05-17 22:46 UTC by aybruhm

The following have been worked on:

- setup redis service on the django test workflow
- removed default throttle rates
- created admin client, admin client API key and override client API key admin add, change and delete permission
- created client and client API key models
- modified get_user_apikey method in the test_views
- override the API key throttling class to support custom scope and rate
- override the default dispatch method on API views to pass the request to the throttling class

**EDIT:** modified the throttle test

2023-05-17 23:33 UTC, aybruhm commented
To create an api key, follow the below process:

1. Create a Client
```python
from academia.models import Client

client = Client.objects.create(
    name="abram-client", 
    email="abram-client@email.com", 
    is_verified=True, 
    client_type=Client.ClientTypes.DEVELOPER
)
client.save()
```

2. Create a Client APIKey
```python
from datetime import datetime import timedelta
from academia.models import ClientAPIKey

_, api_key = ClientAPIKey.objects.create_key(
    name="abram-client-k=apikey", 
    expiry_time=ClientAPIKey.ExpireWhen.THIRTY_DAYS,

    # replace 30 with the value of expiry_time -> could be 30, 60 or 90
    expiry_date=datetime.now() + timedelta(days=int("30") ,

    client=client,
    scope="abram",
    rate=5000,
)

```

`_` is the client_apikey object and `api_key` is the client's API key. Feel free to let me know if you need clarification on something.

2023-05-18 00:46 UTC, devgenix commented on .github/workflows/django.yml
Beautiful work here, thank you for this.

2023-05-18 06:12 UTC, devgenix requested changes

2023-05-18 06:12 UTC, devgenix commented on academia/admin.py
> +class AdminClientAPIKey(admin.ModelAdmin):
Although I see it structured here, I couldn't create a ClientAPIKey in the Django Admin.

2023-05-18 06:12 UTC, devgenix commented on academia/models.py
> +    is_verified = models.BooleanField(default=False)
How is verification done?

2023-05-18 06:30 UTC, devgenix commented
> To create an api key, follow the below process:
> 
>     1. Create a Client
> 
> 
> ```python
> from academia.models import Client
> 
> client = Client.objects.create(
>     name="abram-client", 
>     email="abram-client@email.com", 
>     is_verified=True, 
>     client_type=Client.ClientTypes.DEVELOPER
> )
> client.save()
> ```
> 
>     2. Create a Client APIKey
> 
> 
> ```python
> from datetime import datetime import timedelta
> from academia.models import ClientAPIKey
> 
> _, api_key = ClientAPIKey.objects.create_key(
>     name="abram-client-apikey", 
>     expiry_time=ClientAPIKey.ExpireWhen.THIRTY_DAYS,
> 
>     # replace 30 with the value of expiry_time -> could be 30, 60 or 90
>     expiry_date=datetime.now() + timedelta(days=int("30")),
> 
>     client=client,
>     scope="abram",
>     rate=5000,
> )
> ```
> 
> `_` is the client_apikey object and `api_key` is the client's API key. Feel free to let me know if you need clarification on something.

I understand but does this have to be done programmatically?

2023-05-18 06:35 UTC, merged